"""Auto migration

Revision ID: 561ded1e251e
Revises: 69cebaa856bd
Create Date: 2025-09-18 17:11:26.481146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '561ded1e251e'
down_revision: Union[str, Sequence[str], None] = '69cebaa856bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vpn_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('session_key', sa.String(length=128), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('bytes_rx', sa.BigInteger(), nullable=False),
    sa.Column('bytes_tx', sa.BigInteger(), nullable=False),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('node', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vpn_sessions_server_id'), 'vpn_sessions', ['server_id'], unique=False)
    op.create_index(op.f('ix_vpn_sessions_session_key'), 'vpn_sessions', ['session_key'], unique=False)
    op.create_index(op.f('ix_vpn_sessions_tg_id'), 'vpn_sessions', ['tg_id'], unique=False)
    op.create_index('ix_vpn_sessions_user_active', 'vpn_sessions', ['tg_id', 'ended_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vpn_sessions_user_active', table_name='vpn_sessions')
    op.drop_index(op.f('ix_vpn_sessions_tg_id'), table_name='vpn_sessions')
    op.drop_index(op.f('ix_vpn_sessions_session_key'), table_name='vpn_sessions')
    op.drop_index(op.f('ix_vpn_sessions_server_id'), table_name='vpn_sessions')
    op.drop_table('vpn_sessions')
    # ### end Alembic commands ###
