"""Auto migration

Revision ID: 69cebaa856bd
Revises: 
Create Date: 2025-09-17 22:33:11.745897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69cebaa856bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('original_amount', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('payments', sa.Column('currency', sa.String(length=10), server_default='RUB', nullable=False))
    op.add_column('payments', sa.Column('payment_id', sa.String(length=128), nullable=True))
    op.add_column('payments', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_payments_payment_id'), 'payments', ['payment_id'], unique=False)
    op.add_column('users', sa.Column('preferred_currency', sa.String(length=10), server_default='RUB', nullable=False))
    op.create_index(op.f('ix_users_preferred_currency'), 'users', ['preferred_currency'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_preferred_currency'), table_name='users')
    op.drop_column('users', 'preferred_currency')
    op.drop_index(op.f('ix_payments_payment_id'), table_name='payments')
    op.drop_column('payments', 'metadata')
    op.drop_column('payments', 'payment_id')
    op.drop_column('payments', 'currency')
    op.drop_column('payments', 'original_amount')
    # ### end Alembic commands ###
